require 'sinatra'
require 'braintree'
require 'awesome_print'

Braintree::Configuration.environment = :sandbox
Braintree::Configuration.merchant_id = '23nd25g4kn7gnqbb'
Braintree::Configuration.public_key = '8552x2ym5bvhsycp'
Braintree::Configuration.private_key = '17f3279171d4fd90ee9cd5256be17abf'

# Create a user and display the credit card form
get '/' do
  # create a test user on braintree
  result = Braintree::Customer.create(
    first_name: 'Test',
    last_name: 'User',
  )

  if result.success?
    # get customer id generated by braintree
    @customer_id = result.customer.id

    # generate a client token for the payment method dropin UI
    @client_token = Braintree::ClientToken.generate
    erb :index
  else
    "Creating a customer failed"
  end
end

# Store the customer's credit card details
post '/store' do
  # store the credit card details as a payment method
  result = Braintree::PaymentMethod.create(
    customer_id: params[:customer_id],
    payment_method_nonce: params[:payment_method_nonce]
  )

  if result.success?
    # share the token with the view
    @payment_method = result.payment_method
    # gets list of all plans
    @plans = Braintree::Plan.all
    erb :store
  else
    'Storing card details failed'
  end

end

post '/process' do
  # get a payment method token for the current customer
  @customer = Braintree::Customer.find(params[:customer_id])
  payment_method_token = @customer.payment_methods.first.token

  result = Braintree::Subscription.create(
    plan_id: params[:plan],
    payment_method_token: payment_method_token
  )

  if result.success?
    @subscription = result.subscription
    erb :process
  else
    'Creating a subscription failed'
  end

end
